#
# This file contains lists of object files for our build targets.
# Please keep every file in separate lines to make diff and patching easier.
#

# Game engine
objects = \
	src/action_process.o \
	src/ai_process.o \
	src/button.o \
	src/collision_process.o \
	src/color.o \
	src/component.o \
	src/creature.o \
	src/datetime.o \
	src/dialog.o \
	src/engine.o \
	src/filesystem.o \
	src/font.o \
	src/gui_elements.o \
	src/gui_process.o \
	src/hex_map.o \
	src/hex_object.o \
	src/hex_tile.o \
	src/input_process.o \
	src/json.o \
	src/label.o \
	src/main.o \
	src/mongoose.o \
	src/node.o \
	src/node_utils.o \
	src/noiseutils.o \
	src/notify.o \
	src/parameters.o \
	src/particles.o \
	src/process.o \
	src/random.o \
	src/render_process.o \
	src/surface.o \
	src/texpack.o \
	src/texture.o \
	src/tile.o \
	src/unit_test.o \
	src/widget.o \
	src/wm.o

lua_objects = \
	src/lua/lapi.o \
	src/lua/lauxlib.o \
	src/lua/lbaselib.o \
	src/lua/lbitlib.o \
	src/lua/lcode.o \
	src/lua/lcorolib.o \
	src/lua/lctype.o \
	src/lua/ldblib.o \
	src/lua/ldebug.o \
	src/lua/ldo.o \
	src/lua/ldump.o \
	src/lua/lfunc.o \
	src/lua/lgc.o \
	src/lua/linit.o \
	src/lua/liolib.o \
	src/lua/llex.o \
	src/lua/lmathlib.o \
	src/lua/lmem.o \
	src/lua/loadlib.o \
	src/lua/lobject.o \
	src/lua/lopcodes.o \
	src/lua/loslib.o \
	src/lua/lparser.o \
	src/lua/lstate.o \
	src/lua/lstring.o \
	src/lua/lstrlib.o \
	src/lua/ltable.o \
	src/lua/ltablib.o \
	src/lua/ltm.o \
	src/lua/lua.o \
	src/lua/lundump.o \
	src/lua/lvm.o \
	src/lua/lzio.o
